export enum EstadoPedido {
    PENDIENTE = 'PENDIENTE',
    EN_COCINA = 'EN_COCINA',
    LISTO_PARA_ENTREGA = 'LISTO_PARA_ENTREGA',
    ENTREGADO = 'ENTREGADO',
    PAGADO = 'PAGADO',
    CANCELADO = 'CANCELADO',
}
